language: node_js
node_js:
  - "8"
  - "6"
before_script:
  - git clone --depth 1 https://github.com/APIs-guru/openapi-directory.git
  - git clone --depth 1 https://github.com/mermade/openapi-definitions.git
  - git clone --depth 1 https://github.com/mermade/openapi3-examples.git
#  - git clone --depth 1 https://github.com/SOM-Research/hapi.git
script:
  - node testRunner openapi-directory/APIs/
  - node testRunner openapi-definitions/
  - node testRunner openapi3-examples/pass/
#  - node testRunner hapi/APIs/
